version: '3.9'

services:
  shopsystem-api:
    build: 
        context: ../
        dockerfile: ShopSystem.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ShopSystemDb;User Id=sa;Password=Abcdef@12345;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - shop-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Abcdef@12345
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - shop-network
    volumes:
      - shop-data:/var/opt/mssql

networks:
  shop-network:

volumes:
  shop-data:
